// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Assessment.DATA.Models
{
    [Index("BookBookId", Name = "IX_Book_BookId")]
    public partial class Author
    {
        [Key]
        public int AuthorId { get; set; }
        public string FistName { get; set; }
        public string LastName { get; set; }
        [Column("Book_BookId")]
        public int? BookBookId { get; set; }
        [Column("E-mail")]
        public string EMail { get; set; }

        [ForeignKey("BookBookId")]
        [InverseProperty("Author")]
        public virtual Book BookBook { get; set; }
    }
}