// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Assessment.DATA.Models
{
    public partial class Book
    {
        public Book()
        {
            Author = new HashSet<Author>();
        }

        [Key]
        public int BookId { get; set; }
        public string Isbn { get; set; }
        public string Title { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Ano { get; set; }

        [InverseProperty("BookBook")]
        public virtual ICollection<Author> Author { get; set; }
    }
}