// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Assessment.DATA.Models
{
    public partial class Pais
    {
        [Key]
        public int PaisId { get; set; }
        [StringLength(10)]
        public string PaisName { get; set; }
        [Column(TypeName = "image")]
        public byte[] PaisFlag { get; set; }
        [Column("Pais.Imagem")]
        [StringLength(10)]
        public string PaisImagem { get; set; }
    }
}