// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace amigos.DATA.Models
{
    public partial class Amigo
    {
        public int Id { get; set; }
        public string AmigoName { get; set; }
        public string AmigoLastN { get; set; }
    }
}