// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace amigos.DATA.Models
{
    public partial class Estado
    {
        public int EstadoId { get; set; }
        public string EstadoName { get; set; }
    }
}