// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace amigos.DATA.Models
{
    public partial class Pais
    {
        public int PaisId { get; set; }
        public string PaisName { get; set; }
        public byte[] PaisFlag { get; set; }
        public string PaisImagem { get; set; }
    }
}